### ISSUE TITLE
NaNs in BayesianGPLVM likelihood-gradient

### ISSUE THREAD

**Issue by mrksr** [GPflow/GPflow#301]
While playing around with GPLVM-Models I noticed that sometimes there are NaN-values in the gradients of the likelihood. I have not observed problems with the likelihood itself yet. In search of a small example, I have found the following, which one might argue is a bit of a misuse of GPLVMs, but I think the optimization should still work.

Instead of using the GPLVMs, I tried to "recreate" standard sparse regression on a 1D dataset. I have created some data which can be found on [pastebin](http://pastebin.com/4aEenLKV). The first column. the input, is a Gaussian random walk with some probability of remaining at the same position. The second column, the target, is a (slightly noisy) transform of the input with a linear component and some sine-transformations:
```python
X = gaussian_random_walk()
transform = lambda x: 0.4 * x + 3 * np.sin(x * np.pi * .0025) + 1.5 * np.sin(x * np.pi * 0.1) + 0.8 * np.sin(x * np.pi * 0.3)
Y = transform(X) + some_noise()
```
The only thing special about the data is the fact that there can be multiple observations of a single point in the input space. The problem remains if I add some noise to `X`, thereby forcing them to be different. And since the GPs can model the observations via the noise parameter, this should not be a problem anyway.

SGPR
====
This data can easily be learnt with a standard (sparse) GP regression:
```python
kernel = lambda: GPflow.ekernels.Add((
    GPflow.ekernels.RBF(1),
    GPflow.ekernels.Linear(1),
))

X = data[:, [0]]
Y = data[:, [1]]
num_inducing = 50
Z = X[np.random.permutation(X.shape[0])[:num_inducing]].copy()

m_gpr = GPflow.sgpr.SGPR(
    X,
    Y,
    kernel(),
    Z
)
```
Since the optimization works fine, the gradients are of cause well-defined:
```python
m_gpr._compile()
m_gpr._objective(m_gpr.get_free_state())

Out:
(array([ 1000.95725344]),
 array([ -2.81704226e+02,  -6.40559958e-01,  -6.40560062e-01,
         -6.40560284e-01,  -3.04001075e+00,   1.16295786e+01,
          5.82681802e+01,  -1.18798982e+01,   5.58909405e+00,
          3.17550297e+00,  -8.53468393e+00,   1.57533022e+01,
         -2.78936622e+00,  -5.84108268e+02,  -9.46332675e+00,
         -1.40194934e+00,   5.78258978e+01,   2.63095370e+00,
          5.82681803e+01,  -1.79123485e+02,   1.13670620e+00,
         -7.43702974e-02,  -1.53019223e-01,   1.77508953e+01,
         -3.68175543e+01,  -6.87596823e+00,  -3.90651268e+01,
          3.20169254e+00,  -3.98350333e+00,   4.39886075e+01,
         -4.56802287e+00,   4.92801749e+01,   8.04810090e-01,
          1.41052154e+01,  -7.23761730e+00,   5.95168910e+02,
          8.94047572e+00,  -2.96560545e+00,  -2.46550327e+01,
          1.72454030e+01,   2.07565095e+01,   9.42356752e-01,
          9.25224075e-01,  -1.01081250e+01,  -3.34533879e+01,
         -4.99212923e-01,  -4.76782744e+00,  -2.73890403e+01,
          9.60027822e+00,   5.82681802e+01,   2.97593896e+00,
          2.07328471e-02,   7.39749616e+01,  -3.50988396e+02]))
```

GPLVM
=====
In order to simulate standard Gaussian regression with the BayesianGPLVM, I use the true inputs as the initialization for the latent variables and use a kinda-sensible variance. I also just reuse the position of the inducing points. Lastly, I fix the latent variables.
```python
m_lvm = GPflow.gplvm.BayesianGPLVM(
    X_mean=X,
    X_var=np.ones_like(X) * 1e-1,
    Y=Y,
    kern=kernel(),
    M=num_inducing,
    Z=Z,
    # Setting the prior differently does not change anything:
    # X_prior_mean=np.ones_like(X) * np.mean(X),
    # X_prior_var=np.ones_like(X) * np.var(X),
)

m_lvm.X_mean.fixed = True
m_lvm.X_var.fixed = True
```

This model now shows NaNs in the gradient:
```python
m_lvm._compile()
m_lvm._objective(m_lvm.get_free_state())

Out:
(array([ 1405.9176437]),
 array([             nan,              nan,   2.57392006e-01,
          1.18765660e+01,   3.16422064e-02,  -1.33285666e+00,
         -1.33269030e+00,   5.93233927e-02,              nan,
                     nan,  -2.50538422e-01,   1.36343969e+00,
          9.46894648e-01,  -5.60895659e-01,   5.86809371e-02,
         -2.35575844e+00,   1.01014892e-01,   2.90215995e-01,
          2.33474141e+01,              nan,  -2.41590823e+01,
          6.53458076e-01,  -6.25440986e-01,   1.33456364e+00,
          3.60483842e-01,              nan,  -1.55592021e-01,
          1.11125767e+00,   4.45942942e-02,  -2.73112571e+00,
                     nan,  -3.37639307e-02,   2.55532871e+00,
         -1.50209093e-01,   9.37868310e-01,   1.62371876e-02,
                     nan,   2.55487476e+00,   1.18903649e-01,
         -2.32159878e-02,              nan,   5.53911411e-01,
                     nan,              nan,              nan,
         -5.63527791e+00,   2.91210071e-02,   3.64399269e+00,
         -1.07023839e+00,   8.49490267e-01,  -3.37427557e-02,
         -4.65957019e-01,  -2.63653745e-01,              nan]))
```
Of cause, trying to optimize this model fails.

I do not really know how to debug this, since the problem seems to be in the gradients calculated via tensorflow. Do you think the gradient calculation should work? And if yes, how to go about debugging it?

**Comment by markvdw** [comment]
Wow, super weird. I ran the example and can replicate this. It seems to be related to the scale of the inducing inputs. If I re-initialize `Z` using:
`
m_lvm.Z = rnd.rand(*m_lvm.Z.shape) * 38; m_lvm._objective(m_lvm.get_free_state())
`
I get nan's when the Z range is larger than ~38-39.

I don't have the time to look into this immediately, but I definitely think this should be fixed. @mrksr, could you do some more tests? I.e. does this effect still happen if only the RBF is used? Or only Linear?

**Comment by mrksr** [comment]
I think I have tried this with only RBF before and the problem persisted. I will do some more tests tomorrow.
I also know that it is sensitive to the data somehow. If you only take the first 250 points of this data set, the problem is not there. Sampling different data gives varying results, but I do not really know what aspect is the important one, only that given enough points (I'd say more than 1000), it seems to always happen. Your find might explain this, because given enough points, some pseudo input will land in the 38-39 range.

**Comment by mrksr** [comment]
- Standardizing the input data seems to make this problem go away quite reliably, even for large inputs. So this is a sensible workaround.
- The Problem still exists for only an RBF-kernel, but does _not_  exist for a Linear kernel only.
- (By the way: An `Add`-kernel with one element raises an exception)

Your analysis that this is related to the scale of the data or the pseudo inputs seems spot on.

**Comment by icouckuy** [comment]
> Standardizing the input data seems to make this problem go away quite reliably, even for large inputs (in the sense of many data points). So this is a sensible workaround.
Data with parameter with negligible variance (or vary not at all)  won't work then (though those parameters can be transformed differently, if at all).
