### ISSUE TITLE
LVMs slower on GPU than on CPU

### ISSUE THREAD

**Issue by mrksr** [GPflow/GPflow#327]
Hi everyone!
After updating to tensorflow 0.12.1, LVMs are very slow on GPUs.
Using this code:
```python
import GPflow
import tensorflow as tf
import numpy as np

import pods
pods.datasets.overide_manual_authorize = True

data = pods.datasets.oil_100()
Y = data['X']

Q = 2
M = 20 
N = Y.shape[0]
X_mean = GPflow.gplvm.PCA_reduce(Y, Q)
Z = np.random.permutation(X_mean.copy())[:M]

k = GPflow.ekernels.RBF(2, ARD=True)

m = GPflow.gplvm.BayesianGPLVM(
    X_mean=X_mean,
    X_var=0.1*np.ones((N, Q)),
    Y=Y,
    kern=k,
    M=M,
    Z=Z
)

m.likelihood.variance = 0.01
%time m.optimize(method='L-BFGS-B', disp=True, maxiter=1000)
````

On the same machine, the optimization takes about **1 Minute using only CPUs** and about **10 Minutes when adding one GPU**.

I tried something similar for non-LVMs:
```python
import GPflow
import tensorflow as tf
import numpy as np

X = np.mgrid[0:100:10000j][:, None]
Y = np.sin(X) + 0.1 * np.random.randn(*X.shape)

num_data = X.shape[0]
num_inducing = 200

Z = X[np.random.permutation(num_data)[:num_inducing]].copy()

m = GPflow.sgpr.SGPR(X, Y, GPflow.ekernels.RBF(X.shape[1], ARD=True), Z)

%time m.optimize(method='L-BFGS-B', maxiter=1000)
```
And here, optimization using GPUs was considerably faster by about a factor of 10.

**Comment by mrksr** [comment]
I initially posted this in #181 since a quick skim through the latest changes to GPFlow showed some changes concerning `batch_matmul` and `matmul`, which was discussed as a possible cause there.

**Comment by alexggmatthews** [comment]
Hi guys, we need to use the recently merged #174 to profile it and that will quickly tell us the cause. In general the profiling functionality in tf is excellent so this will quickly help us get to the bottom of this.

**Comment by markvdw** [comment]
@mrksr: So the code was faster in previous versions of TensorFlow?

I had an idea on how to optimise the code in `ekernels.py` yesterday actually. In many locations, we need to do multiple matrix multiplications against a single other matrix or vector. In the current code, I did this using `tf.matmul`, passing the multiple matrices as a 3D tensor, and then multiplying against the other matrix by `tf.tile`ing it to make it a 3D tensor of compatible shape.

I now believe that this is the wrong way to do it, since this requires the right hand tensor to be re-allocated using a much larger size, and just containing copies of itself. The right way is to reshape the left hand 3D tensor into a 2D tensor, do the matrix multiplication, and then reshape back. This should be much faster.

But as @alexggmatthews says, profiling will give a more data driven place where to look.

It would be great if you could help with solving this @mrksr!

**Comment by mrksr** [comment]
The LVMs I was working with were at least as fast on the GPUs as on the CPUs and usually quite a bit faster. I cannot with confidence say however that this also holds for the example I have shown above, but that should be the case.

Is there some example which shows how to use the profiling? I'd be happy to supply some data :).

**Comment by markvdw** [comment]
You can profile code by setting `dump_timeline` in `gpflowrc` to `True`. The timeline can then be viewed in Google chrome using the url `about:trace`.

I could also use help in doing the optimisations in `ekernels.py`, like fixing the tiling issue.

**Comment by alexggmatthews** [comment]
Also are you using float32 or float64? I think that on all GPUs apart from recent ones there will be more than a factor 2 difference in performance between the two.

**Comment by mrksr** [comment]
@markvdw Thanks for pointing me in the right direction! Here are three evaluation timelines:
* [timeline_objective_lvm_cpu.json.gz](https://github.com/GPflow/GPflow/files/744540/timeline_objective_lvm_cpu.json.gz)
* [timeline_objective_lvm_gpu.json.gz](https://github.com/GPflow/GPflow/files/744541/timeline_objective_lvm_gpu.json.gz)
* [timeline_objective_sgpr_gpu.json.gz](https://github.com/GPflow/GPflow/files/744539/timeline_objective_sgpr_gpu.json.gz)

The last one is just for comparison since I think there is nothing wrong with it. While I am not sure how to read the trace in detail, the problem with the LVMs on GPU seems to be a huge amount of memcpy calls.

@alexggmatthews I am using float64 right now. Switching to float32 did not seem to be as easy as just changing the setting in gpflowrc, since if I do that, the minimal SGPR-example above throws `InvalidArgumentError: LLT decomposition was not successful. The input might not be valid.`. This remains if I explicitly cast the data to `np.float32` (which should happen in the `DataHolder` anyway). There might be an easy explanation though, I just did not follow up on it.

**Comment by alexggmatthews** [comment]
@mrksr Re float32 and quick fixes did you try increasing the jitter in the gpflowrc ? Similarly one could add a small white kernel.

**Comment by markvdw** [comment]
Also, deterministic optimisation doesn't work that well with float32. The scipy optimisers are pretty brittle (give up early in the face of even very mild numerical instability) and also have default tolerances that are based on double precision. (This shouldn't result in an LLT decomposition failure, but just for future reference.)

**Comment by markvdw** [comment]
Wow the GPU trace really is a real pain. My hunch is really that it's caused by `tf.tile` operations in for example https://github.com/GPflow/GPflow/blob/master/GPflow/ekernels.py#L117.

**Comment by markvdw** [comment]
Wow the GPU trace really is a real pain. My hunch is really that it's caused by `tf.tile` operations in for example [ekernels.py#L117](https://github.com/GPflow/GPflow/blob/master/GPflow/ekernels.py#L117). In hindsight this is really unnecessary and can be fixed by reshaping `vec`, doing a matrix triangular solve on the vectors, and then reshaping back. This also happens in [ekernels.py#L41](https://github.com/GPflow/GPflow/blob/master/GPflow/ekernels.py#L41) and perhaps in other places.

I would jump in and fix this immediately if I had the time (and a spare GPU), since it should be quicker to fix than to profile to pin down exactly where the problem is.

If you are interested in verifying whether the problem indeed lies in the `ekernel.py` calculations, there are a few things you could do:
- Run `kern.compute_eK...` on the CPU/GPU and see whether this slows down significantly.
- Run a 1D latent space GPLVM using a kernel from `kernels.py` with 1 or 2 quadrature points. This will be super inaccurate, but it should eliminate any speed issues with the kernel computations. If the slow-down persists here, the problem is likely *not* to be in `ekernels.py.

**Comment by mrksr** [comment]
@alexggmatthews A jitter of `1e-2` (`1e-3` is not enough) makes the SGPR example work but for LVMs, it is at least necessary to fix the dtype of the prior mean and variance. If I do this, the decomposition still fails. If I have some time I will try to get this to work and we should probably talk about it in another issue. For now, using float64 is okay for me.

@markvdw Using a normal kernels and 2 quadrature points "fixes" the slow-down.

**Comment by markvdw** [comment]
Great, well I think that implies that the issue is in `ekernels.py`, as I suspected. I even think that fixing the `tf.tile` issue would solve this issue. @mrksr, would you be interested in making this contribution?

**Comment by mrksr** [comment]
I will definitely take a look and see if I can understand how your code works by the end of the week.

**Comment by markvdw** [comment]
Great, feel free to get in touch with me by e-mail with any questions as well. The patch is likely to focus only on a few lines (the ones using `tf.tile`), so I don't think you even need to understand code generally. The biggest reason I can't do it myself is because of the verification on GPUs, which are in short supply in the lab at the moment.

**Comment by mrksr** [comment]
Hmh, the solution to this seems to not be so straightforward. In numpy, functions like `np.linalg.solve` broadcast over the "batch-dimension", but tensorflow seems to not do this. So this does not work in [ekernels.py#L41](https://github.com/GPflow/GPflow/blob/master/GPflow/ekernels.py#L41):
```python
rsm = tf.reshape(scalemat, [N, 1, D, D])  # Reshaped scalemat
rvec  = tf.reshape(vec, [N, M, D, 1])
smIvec = tf.matrix_solve(rsm, rvec)[..., 0]
```
instead of
```python
rsm = tf.tile(tf.expand_dims(scalemat, 1), (1, M, 1, 1))  # Reshaped scalemat
smIvec = tf.matrix_solve(rsm, tf.expand_dims(vec, 3))[:, :, :, 0]  # NxMxD
```

---

A simpler example to illustrate the point. Say we have these matrices:
```python
A = np.arange(16).reshape((4, 4)) + np.eye(4)
b = np.arange(4)[:, None]

As = np.tile(A[None, ...], (3, 1, 1))
bs = b[None, ...]
```
where `As.shape == (3, 4, 4)` and `bs.shape == (1, 4, 4)`. Then
```python
np.linalg.solve(As, bs)
```
works and has shape `(3, 4, 1)`, but
```python
tf.matrix_solve(As, bs).eval()
```
throws `InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 1 for 'MatrixSolve_11' (op: 'MatrixSolve') with input shapes: [3,4,4], [1,4,1].`

Is there a way to force tensorflow to do the broadcasting or did you have another solution in mind?

**Comment by markvdw** [comment]
So that's the error message that caused me to go down the `tf.tile` route in the first place :) Perhaps I should have been clearer about the proposed solution.

The idea is that a matrix solve essentially works vector-by-vector in on the right hand matrix. We want to do a `tf.matrix_solve()` of `scalemat` on `vec`. `scalemat` is `NxDxD`, while `vec` is `NxMxD`.

This should be possible simply by doing `tf.matrix_solve(scalmat, tf.transpose(vec, [0, 2, 1]))`. This gives a matrix of size `NxDxM`. In order to get the expected matrix back, we need to do another transpose, so we get `tf.transpose(tf.matrix_solve(scalmat, tf.transpose(vec, [0, 2, 1])), [0, 2, 1])`.

It should be possible to further optimise the code by making `vec` the right shape to start with, by doing the opposite `tf.expand_dims()` (which can now simply be done using `tensor[:, None, :]` as in numpy).

The example in L117 should be fixed in a similar way, only here a reshape is probably necessary to get all the matrices stacked in the last dimension.

**Comment by markvdw** [comment]
@mrksr Has this been adequately fixed now?

**Comment by mrksr** [comment]
@markvdw Hm, I'd say the answer to this is "it depends".
Last time I used the LVMs with RBF-kernels (and #329 merged), the performance on one of our GPUs was kinda-comparable to the performance on ~8 of our CPUs. This is comparable to the performance observed before the issue. I expect however that `Linear` and `Linear_RBF` are still slow since the tiling still exists there. I did not have time to experiment with this last month though, sadly, since I am not using LVMs right now.
However, as additional information, I remember working on removing the tiles from there when I had some free time and for some reason I cannot remember now, this proved to be not quite so easy compared to the `RBF`-case handled in #329. I do not remember why however and maybe it was just me not seeing the easy solution.

I guess if you want, you can close this issue and just handle the other cases when they come up :).

**Comment by markvdw** [comment]
Hmm, I'll leave it open as a "work in progress" in that case. Lots of models need these kernel expectations, so this issue may be useful when someone wants to contribute.

I would like to see some benchmarks comparing just the kernel expectation evaluation code on GPU vs CPUs, to check whether we're getting the speedup we're expecting in that specific part. It may be that the bottleneck is elsewhere.

**Comment by mrksr** [comment]
If you supply the code you'd like to see tested, I certainly run it sooner or later.

**Comment by markvdw** [comment]
Essentially a comparison of running `kern.compute_eKzxKxz()` and `kern.compute_eKxz()` on CPU and GPU. This is the code that you sped up, and it should increase considerably in speed on a GPU.
